In [2]:
# Numpy Library

# Numpy (Numerical Python) is an open source Python library that's used in almost every field of science and engineering.
# It's the universal standard for working with numerical data in python, and it's at the core of the scientific Pytho and Pydata ecosystems.

# The NumPy library contains a multidimensional array and matrix data structures.
# NumPy can be used to perform a wide variety of Mathematical operations on arrays.
# It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrics and it supplies an enormous library of high-level
# mathematical functions that operate on these arrays and matrics.

# It also has functions for working in domain of linear algebra,fourier transform and matrics.
# NumPy was created in 2005 by Travis Oliphant.It is an open source project and you can use it freely.



In [ ]:
# Why we use NumPy

# In python we have lists that serve the purpose of arrays,but they are slow to process.
# NumPy aims to provide an array object that is up to 50X faster than traditional Python lists.
# The array object in NumPy is called ndarray,it provides a lot of supporting functions that make working with ndarray very easy.
# Arrays are very frequently used in data science,where speed and resources are important.

# NumPy arrays are stored at one continuous place in memory unlike lists,so processess can access and manipulate them very efficiently.
# This behaviour is called locality of reference in computer science.
# This is the main reason why NumPy is faster than lists.
# Also it is optimized to work with latest CPU architectures.


In [ ]:
# Installation of NumPy.

# If you don't have python yet,you might want to consider using Anaconda.
# It's the easiest way to get started.
# The good thing about getting this distribution is the fact that you don't need to worry too much about separately installing NumPy or any of the major packages
# That you'll be using for your data analysis ,like pandas,Scikit-Learn etc.

In [ ]:
# Arrays in NumPy

# 1D array
# 7 2 9 10
# shape:(4,)

# 2D array
# 5.2 3.0 4.5
# 9.1 0.1 0.3
# shape:(2,3)

# 3D arrays

# 1 4 7
# 2 9 7
# 1 3 0
# axis 1

# axis 2
# 7 4
# 7 5
# 0 2

# axis 0
# 1 2
# 4 3
# 7 4

# shape: ( 3,3,2)

In [5]:
! pip install  jupyter numpy



  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
  Using cached webcolors-24.8.0-py3-none-any.whl.metadata (2.6 kB)
Using cached webcolors-24.8.0-py3-none-any.whl (15 kB)
Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
Using cached uri_template-1.3.0-py3-none-any.whl (11 kB)


In [1]:
!pip show numpy


Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [3]:
import numpy as np



In [5]:
arr = np.array([1,2,3,4,5]) # pass a list 

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# Using the tuple to create array.

arr = np.array((1,2,3,4,5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# Dimensions in arrays

arr = np.array(20)

print(arr)
print(type(arr))
print(arr.ndim)


20
<class 'numpy.ndarray'>
0


In [13]:
# 1D array

arr = np.array([1,2,3,4,5,6])

print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [21]:
# 2D array

arr1 = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [23]:
# floating point numbers

arrf = np.array([[1.1,2.2,3.3],[4.4,5.6,6]])

print(arrf)
print(arrf.ndim)

[[1.1 2.2 3.3]
 [4.4 5.6 6. ]]
2


In [25]:
# 3D array

arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])


print(arr3)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [27]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [29]:
# Higher Dimentional Arrays

# An array can have any number of dimensions
# when the array is created,you can defien the number of dimensions by using the ndmin argument.

arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print("Number of Dimensions :", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of Dimensions : 5


In [31]:
a = np.array([[[[[1,2,3,4]]]]])

print(a)
print(a.ndim)

[[[[[1 2 3 4]]]]]
5


In [ ]:
# NumPy Array Indexing

# Array indexing is the same as accessing an array element.
# You can access an array element by referring to its index number.

# The indexes in NumPy arrays start with 0,meaning that the first element has index 0, and the second has index 1 etc.



In [35]:
# Get the first element from the following array.

arr = np.array([1,2,3,4])

print(arr[0])

1


In [37]:
# Get third and sixth and 8th elements from the following array and add them.

m = np.array([41,87,34,56.8,39.23,90,25,10,19,56])

print("The second element is " , m[2])
print("The sixth element is " , m[5])
print("The 8th element is " , m[7])
print("The second element is " , m[2]+m[5]+m[7])

The second element is  34.0
The sixth element is  90.0
The 8th element is  10.0
The second element is  134.0


In [ ]:
# Get 2d array access.

# To access elements from 2d arrays we can use commas separated integers representing the demension and the index of the element
# Think of 2d arrays like a table with rows and columns,where the dimension represents the row and the index represents the column.




In [39]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print("2nd element on 1st row :" , arr[0,1])

2nd element on 1st row : 20


In [43]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print("4th element on 1st row :" , arr[0,3])

4th element on 1st row : 40


In [45]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print("1st element on 2nd row :" , arr[1,0])

1st element on 2nd row : 60


In [47]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print("Last element on 2nd row :" , arr[1,4])

Last element on 2nd row : 100


In [59]:
# Access 3d arrays
# To access elements from 3d array we can use commas separated integers representing the dimensions and the 
# index of the element

arr = np.array([[
    [1,2,3],
    [6,7,8],
    [1,11,12]
    ]])

print(arr[0,1,0])

6


In [67]:
arr = np.array([[[1,2,3],[6,7,8],[1,11,12]]])

print(arr[0,1,2])

8


In [63]:
arr = np.array([[[1,2,3],[6,7,8],[1,11,12]]])

print(arr[0,1,1])

7


In [43]:
# Slicing of numpy arrays

arr = np.array([[
    [1,2,3],[4,5,6],[7,8,9]
    ]])

print(arr[0,2:3])


               

[[7 8 9]]


In [25]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [9]:
arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

[1 3 5 7]


In [11]:
# slicing in 2d arrays

a = np.array([
            [10,20,30,40,50],
            [60,70,80,90,100]
            ])

print(a[1,1:4])




[70 80 90]


In [13]:
a = np.array([
            [10,20,30,40,50],
            [60,70,80,90,100]
            ])

print(a[0,0:3])

[20 30]


In [ ]:
# Arthmatic operations in arrays.
# NumPy has some extra data types,and refer to data types with one character,like i for intergers,

# numpy:- i = intergers,b = booleon,,u = unsigned integers,f = floating point,c = complex float,m = time data,
# M = date time,O = object,S = string,U = unicode string,V = fixed chunk of memory for other type ( void).




In [45]:
# checking the data type of an array.

arr = np.array(
    [1,2,3,4])

print(arr.dtype)

int64


In [47]:
arr = np.array(
    ["animals","bat","cat"])

print(arr.dtype)

<U7


In [49]:
# Creating arrays with a defined data type.

arr = np.array(
    [1,2,3,4],dtype = 'S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [51]:
# creat an array with data types 4 bytes integer.

arr = np.array(
    [1,2,3,4],
    dtype ='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
# NumPy array Shape

# The shape of an array is the number of elements in each dimension.



In [53]:
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])

print(arr.shape)

(2, 4)


In [9]:

import numpy as np

a = np.array([[
            [10,20,30,40,50],
            [60,70,80,90,100],
            [5,6,7,8,9]
            ]])

print(a.shape)


(1, 3, 5)


In [13]:
# Joining NumPu arrays.

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [25]:
# concatenate 2d arrays

arr1 = np.array([
    [1,2],[3,4]])

arr2 = np.array([
    [5,6],[7,8]])

# concatenation with columns.

arr = np.concatenate((arr1,arr2), axis = 1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [27]:
arr1 = np.array([
    [1,2],[3,4]])

arr2 = np.array([
    [5,6],[7,8]])

# concatenation with rows

arr = np.concatenate((arr1,arr2), axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [29]:
# splitting in the arrays in NumPy.

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
# splitting the arrays in 4 parts.

arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [33]:
# ravel & flatten

# converts multidimensional array into 1d array.

m = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

print(m)
print("Dimension is ", m.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is  3


In [35]:
m = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

print(m)
print("Dimension is ", m.ndim)
n = m.ravel()
print(n)
print("Now the new dimension is ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new dimension is  1


In [37]:
m = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]]])

print(m)
print("Dimension is ", m.ndim)
n = m.flatten()
print(n)
print("Now the new dimension is ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is  3
[1 2 3 4 5 6 7 8 9]
Now the new dimension is  1


In [39]:
c = np.array([[[
    [1,2,3],[78,89,25],[45,26,84]]]])

print(c)
print("The Dimension is ", c.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
The Dimension is  4


In [43]:
c = np.array([[[
    [1,2,3],[78,89,25],[45,26,84]]]])

print(c)
print("The Dimension is ", c.ndim)
d = c.ravel()
print(d)
print("Now the new dimension is", d.ndim)

[[[[ 1  2  3]
   [78 89 25]
   [45 26 84]]]]
The Dimension is  4
[ 1  2  3 78 89 25 45 26 84]
Now the new dimension is 1


In [49]:
# Unique Functions

k = np.array([12,14,1,4,5,6,7,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print("The Unique value is :-" ,x)

[12 14  1  4  5  6  7 22 33  7  6  9  1  2 12]
The Unique value is :- [ 1  2  4  5  6  7  9 12 14 22 33]


In [51]:
k = np.array([12,14,1,4,5,6,7,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print("The Unique value is :-" ,x)


[12 14  1  4  5  6  7 22 33  7  6  9  1  2 12]
The Unique value is :- (array([ 1,  2,  4,  5,  6,  7,  9, 12, 14, 22, 33]), array([ 2, 13,  3,  4,  5,  6, 11,  0,  1,  7,  8]))


In [53]:
k = np.array([12,14,1,4,5,6,7,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print("The Unique value is :-" ,x)

[12 14  1  4  5  6  7 22 33  7  6  9  1  2 12]
The Unique value is :- (array([ 1,  2,  4,  5,  6,  7,  9, 12, 14, 22, 33]), array([ 2, 13,  3,  4,  5,  6, 11,  0,  1,  7,  8]), array([2, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1]))


In [55]:
# Delete function in NumPy.

a = np.array([12,13,14,15])

d = np.delete(a, [1])
print(d)

[12 14 15]


In [61]:
x = np.array([
    [2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)

m = np.delete(x, 1, axis = 0)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
